### ISSUE TITLE
sqlite support

### ISSUE THREAD

**Issue by kalafut** [adlio/schema#3]
Hi!

I was working on adding SQLite support. It is all pretty straightforward except for locking. While I _can_ work to add a lock scheme, it's necessarily going to involve polling to try to write the sentinel value, checking I got the lock, handling stale locks, etc. My thought: is it worth it for SQLite? Given the use cases of SQLite, that there can only be one writer, and the migrations are done in a transaction, I think anything beyond a no-op (`""`) lock/unlock is of questionable value. What do you think?

**Comment by adlio** [comment]
Thanks for the help! I've used SQLite with Go just a few times, and I'm no SQLite expert. My initial instinct is that a no-op/lockless solution is harmless.. and a great MVP version... as long as the lack of locking is explained in the README.

That being said, what about a Go-level (rather than DB-level) lock? This package was extracted from a concurrent data pipeline app... and I used a Go sync.Mutex to make sure only the first goroutine did the schema setup... but in production environments, I ended up with unpredictable startup sequencing on different machines... which required a distributed lock. The Postgres DB locking was added to address that.

Distributed access is a problem SQLite would never have, but I can definitely imagine apps with concurrent access from the same process (i.e. goroutines), so that might be worth solving for.

To be clear, I'm definitely open to an enhancement that adds SQLite without locking, as an MVP, though.

Thanks again!

**Comment by kalafut** [comment]
I think Go mutex is a nice upgrade from a no-op and could prevent footguns if you happen to use the migration in concurrently in a process. I'll definitely add that.

I've given some thought to a proper lock and it probably isn't that bad... except it's probably impossible with the current interface 🙂.  If I were to implement against some like `Lock(db *sql.DB)`, it would be fairly straightforward to attempt to claim, retry, block, etc. But since the current interface is just to return some SQL that the Migrator executes, I do not believe there is a single set of SQL in SQLite that could be exec'd and would block in the way the Postgres one does.

One idea would be a second interface that has Lock and Unlock functions which are passed the DB connection. Then in `Migrator.lock()` if the Dialect implements that interface, use it. Otherwise used the SQL/exec as is done today. I think this will provide some flexibility for other databases that may need a little more than one exec to effect the locking. I'll POC this bit and am happy to discard it if need be.

**Comment by adlio** [comment]
Sounds great! I have a friend who needs MySQL support too, so I was about to start  looking into the requirements for that. I have a work deadline coming up next week, but after that I should have some free time to do some releases.
